theme: theme
title: TailLight
author: Jason Morley
email: support@jbmorley.co.uk
description: Set the light on your Microsoft Pro IntelliMouse
image: images/screenshot-default-social@2x.png
baseurl: ""
url: "https://taillight.jbmorley.co.uk"
repository: https://github.com/inseven/taillight
copyright: 2026 <a href="https://jbmorley.co.uk/about">Jason Morley</a>

navigation:
  - title: TailLight
    href: /
  - title: Releases
    href: /releases
  - title: Source
    href: https://github.com/inseven/taillight
  - title: More
    href: https://jbmorley.co.uk/software/
  - title: Donate ❤️
    href: https://jbmorley.co.uk/donate/

footer:
  - title: Privacy Policy
    href: /privacy-policy
  - title: Support
    href: /support
  - title: License
    href: /license

destination: ../_site

defaults:
  - values:
      layout: "page"
